brain: 1.2.3
ptc: ''
cnhe-pcc: ''
etcd: 2.0.0.TEST
prometheus: 3.1.1.XYZ
orchestrator: 1.1.125.F1CD
datanode: 1.0.113.EECB
controlnode: 1.0.179.70C0
pod-pilot: 1.1.60.97B7
pod-controller: 1.1.60.97B7
cnhe-go-ipsec-hub-manager: 1.1.60.97B7
